### ISSUE TITLE
Issue with the world map magnifying glass

### ISSUE THREAD

**Issue by coldwinter18** [Jaliborc/PetTracker#141]
**Running Software (issues missing this information will be deleted):**

- Addon version: 8.3.0 , Jan 17, 2020

**Have you read the changelog? (please don't waste our time)**
Mark if read. yes

**Describe the bug**
When I try to click the magnifying glass on the world map so I can hide all these battle pet icons, I cannot click any option but instead, the options disappear. So I ended up typing "hide" on the search.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'world map magnifying glass'
2. Click on 'left click'
3. Try to uncheck the "species"
4. See error 'nothing happens'

**Expected behaviour**
Hide all the species icon from the world map

**Screenshots**
https://imgur.com/etcdi0B

**Error Logs**
No error logs, it does not accept my unclick or click command.

**Comment by Htremob** [comment]
i'm have this problem to its not so funn :'(

**Comment by Neurotoxin001** [comment]
+

**Comment by sauljaffe** [comment]
I have the opposite problem.  I can't get the species to appear (the menu just goes away) and there's no search bar.

**Comment by clmcgrath** [comment]
changelog says the dropdown isn't functional right now ,  is there a command that we can use to replace this functionality ?

**Comment by MarkM793** [comment]
I have the same issue - Magnifying glass makes the drop down appear, but clicking anything makes the drop down close and has no effect i.e.  The filters are exactly the same.  This issue is so annoying that I have disabled the complete add-on right now (and when I do, I can use the map magnifier fine to filter out things) - The reason this is so annoying (sometimes) is that in a new area the map has so many icons of different sorts that it can be hard to find what you need, so you have to be able to turn filters of and on to find stuff

**Comment by aleczk** [comment]
Same problem here, was about to make a topic here but found this one. I even made a Gif.

I disabled ALL addons except the PetTracker and its modules to see if works but no luck.

[InstantGif_2020 02 15-05 29](https://user-images.githubusercontent.com/16522249/74582494-48e95d80-4f9b-11ea-8556-710328374285.gif)

**Comment by sauljaffe** [comment]
At least you get the species shown, and the search bar.  I get neither.  I'm having a real tough time finding the new void pets without PetTracker being functional.  I also tried turning off all add-ons to see if the problem was fixed and sadly, it was still broken.  Worse, Buggrabber/Bugsack show no errors.

**Comment by aleczk** [comment]
> At least you get the species shown, and the search bar. I get neither. I'm having a real tough time finding the new void pets without PetTracker being functional. I also tried turning off all add-ons to see if the problem was fixed and sadly, it was still broken. Worse, Buggrabber/Bugsack show no errors.

Probably you could delete your saved variables and reinstall, since the default is to show everything. Twitch has this option

**Comment by sauljaffe** [comment]
> > At least you get the species shown, and the search bar. I get neither. I'm having a real tough time finding the new void pets without PetTracker being functional. I also tried turning off all add-ons to see if the problem was fixed and sadly, it was still broken. Worse, Buggrabber/Bugsack show no errors.
> 
> Probably you could delete your saved variables and reinstall, since the default is to show everything. Twitch has this option
> 
> Also, problem not fixed yet. Gonna try using an old version of the addon to see if it fixes it.

Ok, tried to delete the variables and reinstall.  Twice.  Deleted the add-on and then re-installed in.  No change.  Still can't see any species on the map.  Still can't turn them on via the menu.  Still don't see a search bar and can't search.

**Comment by Jaliborc** [comment]
Fixed
