### ISSUE TITLE
Re-opening bug #173

### ISSUE THREAD

**Issue by sauljaffe** [Jaliborc/PetTracker#174]
Please see bug #173

THE INSTALL IS NOT CORRUPTED.  THESE ARE BUGS.

**Comment by ghostpets** [comment]
I noticed in the post you referenced [here](https://github.com/Jaliborc/PetTracker/issues/173), your errors #2 and #3 are referring to folders from previous versions (since PetTracker 8.3.1 and later, PetTracker_Breeds\PetTracker_Breeds.toc and PetTracker_Switcher\PetTracker_Switcher.toc are no longer used).

As of the latest version, PetTracker creates 4 folders:  PetTracker, PetTracker_Battle, PetTracker_Config, and PetTracker_Journal (4 add-on modules of the same names show up in WoW, except without the underscore characters).

Anyways, here are 2 things to try and if you haven't already tried them:

1.  Go to your WoW add-ons folder (usually something like C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns).  In that folder, delete all folders with PetTracker in the name.  That should get rid of any old add-on remnants that Twitch maybe failed to delete.

2.  You will also want to delete your PetTracker saved settings that you have stored that may be causing issues.  They are in C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\SavedVariables or C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\(YourAccountName)\SavedVariables or something like that.  You will want to remove any PetTracker files (namely PETTRACKER.LUA and PETRACKER.LUA.BAK) from the folder, but don't delete any files there without backing them up somewhere else on your computer first (while the PetTracker settings and many other add-on settings saved there are somewhat trivial, some have important stuff, like Rematch has your saved teams there).

Then after doing those two things you can re-install the add-on in Twitch.

If you have already tried these steps, I apologize.  It's all I can think of for now.
