### ISSUE TITLE
Error message when clicking on the world map icon of a pet.

### ISSUE THREAD

**Issue by Zaldoras** [Jaliborc/PetTracker#207]
For months now, I've been getting the same error message when I click on an pet icon on the world map:

Message: ...s\PetTracker\addons\main\classes\abstract\specie.lua:26: attempt to index a nil value
Time: Fri Aug 14 18:32:10 2020
Count: 1
Stack: ...s\PetTracker\addons\main\classes\abstract\specie.lua:26: attempt to index a nil value
[string "@Interface\AddOns\PetTracker\addons\main\classes\abstract\specie.lua"]:26: in function `GetID'
[string "@Interface\AddOns\PetTracker\addons\main\classes\abstract\pet.lua"]:33: in function `Display'
[string "@Interface\AddOns\PetTracker\addons\main\classes\maps\speciePin.lua"]:67: in function <...ns\PetTracker\addons\main\classes\maps\speciePin.lua:65>

Locals: self = <table> {
 specie = 272
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"

**Comment by leandrodcarvalho** [comment]
I have the same problem, since there is no answer since August 14 for this matter I managed to do a "quick fix" for this, I'm not the developer, just trying to help.

Replace lines 33 to 36 with this:
`  if self:GetSpecie() then
    PetJournal_SelectSpecies(PetJournal, self:GetSpecie())
  elseif self:GetID() then
	PetJournal_SelectPet(PetJournal, self:GetID())
`

This is caused when you click on a pet that you are missing, it tries to find the best you OWN.
