### ISSUE TITLE
Hide tracker if no pets found in zone / completed

### ISSUE THREAD

**Issue by addonaddict** [Jaliborc/PetTracker#250]
**Is your feature request related to a problem? Please describe.**
"Pets" tab is showing 100% of the time, even if all pets are collected or no pets are found (this is the case here)
![image](https://user-images.githubusercontent.com/73442541/103145227-c7a73f00-4704-11eb-8d4b-2097d12ad214.png)

**Describe the solution you'd like**
Pets tab should disappear unless any of the 2 conditions above are not met

**Describe alternatives you've considered**
you can make this a toggle in options for those who might want it to show, for whatever reason..

thank you

**Comment by vttale** [comment]
Agreed,  I leave this setting off because I don't want empty headers on my screen, and as I have a very large collection there is almost nowhere that it isn't 100% or empty.   I would like to be more aware if I enter a place that has a pet I somehow don't have yet, but having it on all the time leads to something like "banner blindness" and it becomes wasted visual real estate.
