### ISSUE TITLE
Search field in map missing

### ISSUE THREAD

**Issue by Mike160770** [Jaliborc/PetTracker#271]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.1.0
 - Server patch: 9.1.5 (40906 release x64)

 **Have you read the changelog? (please don't waste our time)**
Yes

**Describe the bug**
In the World Map the field where you could search e.g. for pets that are missing and/or not maximized does not show up anymore

**Comment by Lustie1984** [comment]
Iam having the same issue. It was working just fine the other day.  I went to use it today and  there is no search button or anything. please fix this i really love this addon and it sucks it is not working correctly

**Comment by kanjigirl** [comment]
There's no search bar on the map, no way to turn off or limit the number of pet icons in the map - there are hundreds and I have to just disable the addon completely to hide them.

**Comment by Kamaw** [comment]
Hey I have the same problem there is no search bar on the map and I don't see any pet on the map. please fix it quickly. Thanks in advance.

**Comment by pierre2410** [comment]
same problem for me

**Comment by Reddyo12** [comment]
Switching to 9.0.1. version seems to fix the map bar problem

**Comment by Mike160770** [comment]
> Switching to 9.0.1. version seems to fix the map bar problem

Do the pets from Shadowlands still show up in the 9.0.1 version?

**Comment by jorgeaff** [comment]
Same problem here. No search field and the map is full of pet icons.

**Comment by Lustie1984** [comment]
yes if you switch to the 9.0.1 on it does show them just don't do the beta one click on the one before the beta one and it works just fine    On Friday, November 12, 2021, 03:18:20 PM EST, Mike160770 ***@***.***> wrote:  
 
 



Switching to 9.0.1. version seems to fix the map bar problem


Do the pets from Shadowlands still show up in the 9.0.1 version?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lustie1984** [comment]
thank you very much for this information I am very happy now:) 
    On Friday, November 12, 2021, 04:46:58 AM EST, Reddyo12 ***@***.***> wrote:  
 
 


Switching to 9.0.1. version seems to fix the map bar problem

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NovaKuper** [comment]
Still a problem here. No search field and the map is full of pet icons.
I switched to the 9.0.1 version (**10/16/2020 PetTracker-9.0.1-9.0.1.zip Release 9.0.1**)  search field shows up but pets from Shadowlands don't

**Comment by lolabornack** [comment]
I currently still have the issue of no search box. Even with the newest update 9.1.1. If I install 9.0.1 it will have the search box but all the shadowland pets will be missing. Any install later than 9.0.1 will remove the search box. I am not sure if this helps. Thank you! I really love and appreciate this addon and hope it works again soon. :)

**Comment by Jaliborc** [comment]
Fixed
