### ISSUE TITLE
Zone Tracker checkbox disappeared with new update

### ISSUE THREAD

**Issue by fullhouseison** [Jaliborc/PetTracker#48]
Maybe I'm missing something, but I used to be able to hide pets on the map by checking off the zone tracker box, now they are cluttering up my map with no way to turn it off aside from straight up disabling the addon.

**Comment by ChadCloman** [comment]
This. When I pull up the Darkshore map, it's almost nothing but pets. And I can't find any way to disable it.

**Comment by ChadCloman** [comment]
To remove the display of the pets on the map, do the following:

1. In your WoW program directory, go to the `Interface\AddOns\PetTracker\Features` directory.
1. Using your favorite text editor, edit the MapCanvas.lua file.
1. Find '`function MapCanvas:Draw`'
1. Insert a new line, directly underneath that line, as follows:
    * `do return end`

This will be erased after the next update, but hopefully the problem will be fixed by then.
