### ISSUE TITLE
Option to not show trainer icons on map/unlink from world quest visibility

### ISSUE THREAD

**Issue by EricBoe** [Jaliborc/PetTracker#77]
The trainer icons on the map can be pretty large and obtrusive for non-pet battle play, so I would want to play other parts of the game with them hidden. If, however, I wanted to look at the map to find a pet battle world quest i would have to toggle them on temporarily; currently, the world quests are only visible if the trainer icons are also visible.

I can think of two pretty clean solutions to this - 

Unlink the pet tracker trainer icons from the pet battle icons on the map - i.e. you could show neither, the default pet battle icons + world quests, the pet tracker icons, or both.

Or, create an option that allows the user to only use the default pet battle icons when "battles" is checked in the map's menu.

Ultimately all I really want is to be able to see that pet battle world quests are on the map while the trainer icons aren't also visible.

**Comment by BarnacleBob** [comment]
I agree these icons, while nice, are too large for normal play.  A toggle for them would be great.

**Comment by TurduckenMcNugget** [comment]
You really need to allow us to turn these off and here's why:

I'm in Dalaran, there are huge icons where the dalaran pet battles are so that I can't easily see if there's a green paw indicating an available battle.  Looking at the Broken Shores I can see a green paw for an available battle.  If I click the hourglass on the map and turn off Battles, then it removes those big icons, but now there are no green paws shown.

So, with your giant icons it is impossible to see on the map whether that tamer is up and active.  And the only way we've found to remove displaying of those icons also makes it impossible to see if that quest is up.

**Comment by EricBoe** [comment]
Just to clarify something - I am not having issues with the world quest icons being visible - at least for me, they are being rendered in front of the trainer icons. I'd just like to be able to also see them when I have the trainer icons turned off because sometimes I do those world quests as part of emissaries or whatever when I'm not really exclusively pet battling and won't want the pet tracker icons all over the map.

**Comment by Jaliborc** [comment]
Added option
